"""Auditable total-return backtest using the private FinMind cache.

No raw market rows are committed.  This module writes only aggregate metrics
and the exact assumptions that produced them.
"""

from __future__ import annotations

import argparse
import json
import math
import os
from statistics import pstdev
from collections import defaultdict
from dataclasses import dataclass
from datetime import datetime, timezone
from pathlib import Path
from typing import Any


ROOT = Path(__file__).resolve().parent
BUY_FEE = 0.001425
SELL_FEE = 0.001425
STOCK_SELL_TAX = 0.003
ETF_SELL_TAX = 0.001
SLIPPAGE_BPS = 10
LOOKBACK = 60
HOLDING = 20
PICKS = 5


def load(path: Path) -> Any:
    return json.loads(path.read_text(encoding="utf-8-sig"))


def num(value: Any) -> float:
    try:
        return float(value or 0)
    except (TypeError, ValueError):
        return 0.0


def cash_dividends(rows: list[dict[str, Any]]) -> dict[str, float]:
    """Cash dividend per share by ex-dividend date.

    The distribution fields are per-share amounts in the dividend policy
    dataset.  Reinvestment happens at that date's closing price; stock
    dividends are separately counted and reported as a data limitation until
    a licensed adjusted-price feed is available.
    """
    result: dict[str, float] = defaultdict(float)
    for row in rows:
        day = str(row.get("CashExDividendTradingDate") or "")[:10]
        if not day:
            continue
        result[day] += num(row.get("CashEarningsDistribution")) + num(row.get("CashStatutorySurplus"))
    return result


def stock_dividend_events(rows: list[dict[str, Any]]) -> int:
    return sum(
        1
        for row in rows
        if num(row.get("StockEarningsDistribution")) or num(row.get("StockStatutorySurplus"))
    )


def stock_dividend_factors(rows: list[dict[str, Any]]) -> dict[str, float]:
    factors: dict[str, float] = defaultdict(lambda: 1.0)
    for row in rows:
        day = str(row.get("StockExDividendTradingDate") or "")[:10]
        stock = num(row.get("StockEarningsDistribution")) + num(row.get("StockStatutorySurplus"))
        if day and stock > 0:
            # Stock dividend is stated in nominal dollars per share; NT$10
            # corresponds to one additional share.
            factors[day] *= 1 + stock / 10
    return factors


def stock_dividend_validation(payload: dict[str, Any]) -> tuple[int, int, float | None]:
    policies = {str(row.get("StockExDividendTradingDate") or "")[:10]: row for row in payload.get("TaiwanStockDividend", [])}
    errors: list[float] = []
    events = 0
    for action in payload.get("TaiwanStockDividendResult", []):
        row = policies.get(str(action.get("date") or "")[:10])
        if not row:
            continue
        stock = num(row.get("StockEarningsDistribution")) + num(row.get("StockStatutorySurplus"))
        if stock <= 0:
            continue
        events += 1
        before, after = num(action.get("before_price")), num(action.get("after_price"))
        cash = num(row.get("CashEarningsDistribution")) + num(row.get("CashStatutorySurplus"))
        expected_after = max(0.0, before - cash) / (1 + stock / 10)
        if before > 0 and after > 0 and expected_after > 0:
            errors.append(abs(after / expected_after - 1))
    return events, len(errors), (sum(errors) / len(errors) if errors else None)


@dataclass
class Series:
    code: str
    values: dict[str, float]
    stock_dividend_events: int
    entry_date: str | None = None
    exit_date: str | None = None


def total_return_series(code: str, payload: dict[str, Any], entry_date: str | None = None,
                        exit_date: str | None = None) -> Series:
    prices = sorted(payload.get("TaiwanStockPrice", []), key=lambda row: str(row.get("date", "")))
    dividends = cash_dividends(payload.get("TaiwanStockDividend", []))
    stock_factors = stock_dividend_factors(payload.get("TaiwanStockDividend", []))
    values: dict[str, float] = {}
    previous = 0.0
    wealth = 1.0
    for row in prices:
        day = str(row.get("date", ""))[:10]
        close = num(row.get("close"))
        if not day or close <= 0:
            continue
        if previous > 0:
            price_return = close / previous
            reinvestment = 1.0 + max(0.0, dividends.get(day, 0.0)) / close
            wealth *= price_return * reinvestment * stock_factors.get(day, 1.0)
        values[day] = wealth
        previous = close
    return Series(code, values, stock_dividend_events(payload.get("TaiwanStockDividend", [])), entry_date, exit_date)


def official_benchmark_series(path: Path) -> Series:
    """Load the TWSE Taiwan 50 total-return index as the benchmark.

    This avoids treating the 0050 ETF's split-affected raw price history as
    an index benchmark.  The source file is generated by the official TWSE
    TAI50I endpoint and contains ``date``/``total_return`` rows.
    """
    rows = load(path)
    values = {
        str(row.get("date"))[:10]: num(row.get("total_return"))
        for row in rows
        if isinstance(row, dict) and row.get("date") and num(row.get("total_return")) > 0
    }
    if len(values) < 20:
        raise SystemExit("official Taiwan 50 total-return benchmark is missing or too short")
    base = values[min(values)]
    values = {day: value / base for day, value in values.items()}
    return Series("0050_TR", values, 0)


def max_drawdown(returns: list[float]) -> float:
    equity = peak = 1.0
    minimum = 0.0
    for value in returns:
        equity *= 1 + value
        peak = max(peak, equity)
        minimum = min(minimum, equity / peak - 1)
    return minimum


def annualized(total_return: float, days: int) -> float | None:
    if days < 2 or total_return <= -1:
        return None
    return (1 + total_return) ** (252 / days) - 1


def run_period(series: dict[str, Series], dates: list[str], is_etf: bool = False,
               lookback: int = LOOKBACK, holding: int = HOLDING, picks_count: int = PICKS,
               ranking_mode: str = "momentum") -> dict[str, Any]:
    returns: list[float] = []
    trades = 0
    for index in range(lookback, len(dates) - holding, holding):
        signal, entry, exit_ = dates[index], dates[index + 1], dates[index + holding]
        ranked = []
        for code, item in series.items():
            if item.entry_date and signal < item.entry_date:
                continue
            if item.exit_date and exit_ >= item.exit_date:
                continue
            if signal in item.values and dates[index - lookback] in item.values and entry in item.values and exit_ in item.values:
                momentum = item.values[signal] / item.values[dates[index - lookback]] - 1
                if ranking_mode == "risk_adjusted":
                    trail = [item.values[day] for day in dates[max(0, index - 20):index + 1] if day in item.values]
                    if len(trail) < 10:
                        continue
                    daily = [trail[pos] / trail[pos - 1] - 1 for pos in range(1, len(trail))]
                    momentum /= max(pstdev(daily), 0.01)
                gross = item.values[exit_] / item.values[entry] - 1
                ranked.append((momentum, gross))
        picks = sorted(ranked, reverse=True)[:picks_count]
        if not picks:
            continue
        gross = sum(item[1] for item in picks) / len(picks)
        slippage = 2 * SLIPPAGE_BPS / 10_000
        sell_tax = ETF_SELL_TAX if is_etf else STOCK_SELL_TAX
        net = (1 + gross) * (1 - BUY_FEE - SLIPPAGE_BPS / 10_000) * (1 - SELL_FEE - sell_tax - SLIPPAGE_BPS / 10_000) - 1
        returns.append(net)
        trades += len(picks)
    total = math.prod(1 + item for item in returns) - 1 if returns else 0.0
    return {"totalReturn": total, "annualizedReturn": annualized(total, len(dates)), "mdd": max_drawdown(returns), "periods": len(returns), "trades": trades}


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--cache-dir", type=Path, default=Path(os.environ.get("DATA_CACHE_DIR", ROOT / ".private-data-cache")))
    parser.add_argument("--output", type=Path, default=ROOT / "data" / "total-return-backtest-status.json")
    parser.add_argument("--benchmark-file", type=Path, default=None,
                        help="official TWSE Taiwan 50 total-return JSON")
    args = parser.parse_args()
    stocks = args.cache_dir / "finmind-backtest-v2" / "stocks"
    payloads = {path.stem: load(path) for path in stocks.glob("*.json")}
    official_dir = args.cache_dir / "official-listing-history-v1"
    certification_path = official_dir / "universe-certification.json"
    universe_status = load(certification_path) if certification_path.exists() else {}
    evidence_path = official_dir / "semiconductor-membership-evidence.json"
    evidence = load(evidence_path) if evidence_path.exists() else {}
    if "0050" not in payloads:
        raise SystemExit("benchmark 0050 is not cached")
    # The research run itself follows the same strict inclusion rule as the
    # promotion gate: no official entry-date evidence, no stock in the run.
    fixed_codes = {
        item.strip() for item in os.environ.get("FIXED_UNIVERSE_CODES", "").split(",")
        if item.strip().isdigit() and len(item.strip()) == 4
    }
    verified_codes = {
        code for code, item in evidence.items()
        if isinstance(item, dict) and item.get("entryDate")
    }
    universe = {
        code: total_return_series(
            code,
            data,
            evidence.get(code, {}).get("entryDate"),
            evidence.get(code, {}).get("exitDate"),
        )
        for code, data in payloads.items()
        if code != "0050" and (code in verified_codes or code in fixed_codes)
    }
    if not universe:
        raise SystemExit("no officially verifiable stocks available for strict research backtest")
    benchmark = official_benchmark_series(args.benchmark_file) if args.benchmark_file else total_return_series("0050", payloads["0050"])
    # Do not intersect every constituent's calendar: that would discard the
    # early history merely because a later IPO did not yet exist.  The benchmark
    # calendar is the master calendar; run_period admits a stock only when it
    # has the required lookback, entry and exit observations.
    calendar = sorted(benchmark.values)
    if len(calendar) < 100:
        raise SystemExit("insufficient benchmark history")
    train_end, validation_end = int(len(calendar) * 0.6), int(len(calendar) * 0.8)
    splits = {"train": calendar[:train_end], "validation": calendar[train_end:validation_end], "test": calendar[validation_end:]}
    results = {name: run_period(universe, days) for name, days in splits.items()}
    benchmark_results = {name: run_period({benchmark.code: benchmark}, days, is_etf=True) for name, days in splits.items()}
    performance_passed = (
        results["validation"]["periods"] >= 5
        and results["test"]["periods"] >= 5
        and results["validation"]["totalReturn"] > benchmark_results["validation"]["totalReturn"]
        and results["test"]["totalReturn"] > benchmark_results["test"]["totalReturn"]
    )
    validations = [stock_dividend_validation(data) for code, data in payloads.items() if code != "0050"]
    stock_events = sum(item[0] for item in validations)
    stock_matches = sum(item[1] for item in validations)
    total_error = sum((item[2] or 0.0) * item[1] for item in validations)
    stock_error = total_error / stock_matches if stock_matches else None
    # Never promote a result that has not modelled the share-count adjustment
    # for stock dividends.  Cash dividends are already reinvested, but using
    # this result as a buy signal would otherwise overstate confidence.
    stock_adjustment_validated = stock_matches >= 20 and stock_error is not None and stock_error <= 0.03
    # The current cache universe is assembled from companies that pass today's
    # completeness gate.  Do not promote it until historical membership is
    # reconstructed at each rebalance date, otherwise performance can contain
    # survivorship bias.
    # This is intentionally derived only from the strict official verifier;
    # price history or today's membership must never open this gate.
    point_in_time_universe = bool(universe_status.get("certified", False))
    promotion_blocked = (
        not stock_adjustment_validated
        or not point_in_time_universe
        or len(calendar) < 500
        or bool(fixed_codes)
    )
    output = {
        "schemaVersion": 1,
        "generatedAt": datetime.now(timezone.utc).isoformat(),
        "status": "research_only" if performance_passed and promotion_blocked else ("candidate" if performance_passed else "rejected"),
        "universe": {"stocks": len(universe), "benchmark": "0050", "benchmarkTradingDays": len(calendar), "pointInTimeMembership": point_in_time_universe, "inclusionRule": "explicit fixed basket" if fixed_codes else "official entry-date evidence only"},
        "strategy": {"name": "60-day total-return momentum", "lookbackDays": LOOKBACK, "holdingDays": HOLDING, "picks": PICKS},
        "costs": {"buyFee": BUY_FEE, "sellFee": SELL_FEE, "stockSellTax": STOCK_SELL_TAX, "etfSellTax": ETF_SELL_TAX, "oneWaySlippageBps": SLIPPAGE_BPS},
        "dividends": {"cash": "reinvested at ex-dividend date close", "stockDividendEvents": stock_events, "stockDividendMatchedEvents": stock_matches, "stockDividendReferencePriceError": stock_error, "stock": "share count adjusted using validated ex-right reference-price mapping"},
        "splits": {name: {"strategy": results[name], "benchmark0050": benchmark_results[name]} for name in splits},
        "promotionRule": "Both validation and untouched test must beat 0050 after costs, with at least 5 holding periods each.",
        "promotionBlocked": promotion_blocked,
        "promotionBlockers": [
            blocker for blocker, active in {
                "stock_dividend_adjustment": not stock_adjustment_validated,
                "survivorship_bias": not point_in_time_universe,
                "fixed_universe_only": bool(fixed_codes),
                "short_history": len(calendar) < 500,
            }.items() if active
        ],
    }
    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(json.dumps(output, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
    print(json.dumps(output, ensure_ascii=False))


if __name__ == "__main__":
    main()
